### ISSUE TITLE
Including a license?

### ISSUE THREAD

**Issue by mbjoseph** [sizhuoli/TreeCountSegHeight#1]
Thank you for open sourcing this and sharing your work with the community. However, I noticed that there is no LICENSE file in the repo. I'm interested in using some of the code and would appreciate a better understanding of the licensing terms. Could you please consider adding a LICENSE file to the repo?

**Comment by sizhuoli** [comment]
Hi, thanks for your interest and the nice suggestion. I have just added a license to it.

**Comment by mbjoseph** [comment]
Thank you! 🚀
